name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: please release without release note
        run: |
          ls
          npm install --save-dev release-please
          npx release-please github-release --repo-url https://github.com/$GITHUB_REPOSITORY --release-type simple --token $GITHUB_TOKEN
